# Generated by Django 4.2.30 on 2026-05-16 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor', models.CharField(default='#5eead4', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('aldeia', models.CharField(blank=True, max_length=120, null=True)),
                ('terra_indigena', models.CharField(blank=True, max_length=120, null=True, verbose_name='Terra indígena')),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(default='MA', max_length=2)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas_ativas', to='academico.anoletivo')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sala', models.CharField(blank=True, max_length=30, null=True)),
                ('turno', models.CharField(blank=True, max_length=30, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.anoletivo')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('formacao', models.CharField(blank=True, max_length=150, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='academico.escola')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do professor',
                'verbose_name_plural': 'Perfis dos professores',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='ParecerAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(blank=True, choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], null=True)),
                ('texto', models.TextField()),
                ('encaminhamentos', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='academico.aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareceres_professor', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_alunos', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Parecer descritivo do aluno',
                'verbose_name_plural': 'Pareceres descritivos dos alunos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('ATENCAO', 'Atenção'), ('CRITICO', 'Crítico'), ('SUCESSO', 'Sucesso')], default='INFO', max_length=20)),
                ('resolvida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_gestao', to='academico.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_gestao', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_gestao', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Notificação da gestão',
                'verbose_name_plural': 'Notificações da gestão',
                'ordering': ['resolvida', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('MATRICULA', 'Matrícula'), ('TRANSFERENCIA', 'Transferência'), ('EVASAO', 'Evasão'), ('RETORNO', 'Retorno'), ('APROVACAO', 'Aprovação'), ('REPROVACAO', 'Reprovação'), ('OBSERVACAO', 'Observação pedagógica')], default='OBSERVACAO', max_length=30)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='academico.aluno')),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_alunos', to='academico.anoletivo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_registrados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_alunos', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Histórico do aluno',
                'verbose_name_plural': 'Históricos dos alunos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diário de classe'), ('BOLETIM', 'Boletim'), ('FREQUENCIA', 'Frequência'), ('PARECER', 'Parecer'), ('RELATORIO', 'Relatório'), ('OUTRO', 'Outro documento')], max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('IMPRESSO', 'Impresso'), ('ASSINADO', 'Assinado'), ('ARQUIVADO', 'Arquivado')], default='GERADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='academico.aluno')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Documento gerado',
                'verbose_name_plural': 'Documentos gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('AULA', 'Dia letivo'), ('FERIADO', 'Feriado'), ('REUNIAO', 'Reunião'), ('AVALIACAO', 'Avaliação'), ('PLANEJAMENTO', 'Planejamento'), ('EVENTO', 'Evento escolar')], default='EVENTO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='academico.anoletivo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='academico.escola')),
            ],
            options={
                'verbose_name': 'Evento do calendário escolar',
                'verbose_name_plural': 'Eventos do calendário escolar',
                'ordering': ['data_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=120)),
                ('acao', models.CharField(max_length=160)),
                ('objeto', models.CharField(blank=True, max_length=180, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria do sistema',
                'verbose_name_plural': 'Auditorias do sistema',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diário de classe'), ('BOLETIM', 'Boletim'), ('FREQUENCIA', 'Frequência'), ('PARECER', 'Parecer'), ('RELATORIO', 'Relatório')], max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_documentos', to='academico.aluno')),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_documentos', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Assinatura de documento',
                'verbose_name_plural': 'Assinaturas de documentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academico.turma'),
        ),
        migrations.CreateModel(
            name='AlertaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('nivel', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=20)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorTurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_professores', to='academico.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_pedagogicos', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_professores', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Vínculo professor/turma/disciplina',
                'verbose_name_plural': 'Vínculos professor/turma/disciplina',
                'ordering': ['turma__nome', 'disciplina__nome'],
                'unique_together': {('professor', 'turma', 'disciplina', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')])),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 1')),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 2')),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 3')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'bimestre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, '2ª Feira'), (2, '3ª Feira'), (3, '4ª Feira'), (4, '5ª Feira'), (5, '6ª Feira'), (6, 'Sábado')])),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='Exemplo: 1 para 1º horário, 2 para 2º horário.', verbose_name='Horário')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno')], max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Horário de aula',
                'verbose_name_plural': 'Horários de aula',
                'ordering': ['dia_semana', 'ordem', 'hora_inicio'],
                'unique_together': {('professor', 'turma', 'disciplina', 'dia_semana', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('aluno', 'disciplina', 'data')},
            },
        ),
        migrations.CreateModel(
            name='FechamentoBimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')])),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='ABERTO', max_length=20)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_bimestrais', to='academico.disciplina')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_bimestrais', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Fechamento bimestral',
                'verbose_name_plural': 'Fechamentos bimestrais',
                'ordering': ['turma__nome', 'bimestre', 'disciplina__nome'],
                'unique_together': {('turma', 'disciplina', 'bimestre')},
            },
        ),
    ]
