# Generated by Django 6.0.5 on 2026-05-17 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_frequencia_status_oficial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField(default=2026)),
                ('aulas_previstas', models.PositiveSmallIntegerField(default=0)),
                ('aulas_dadas', models.PositiveSmallIntegerField(default=0)),
                ('frequencias_lancadas', models.PositiveIntegerField(default=0)),
                ('conteudos_registrados', models.PositiveIntegerField(default=0)),
                ('percentual_frequencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PENDENTE', 'Pendente'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto')], default='ABERTO', max_length=20)),
                ('pendencias', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_mensais', to='academico.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_mensais', to='academico.disciplina')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_mensais_realizados', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_mensais', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_mensais', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Fechamento mensal oficial',
                'verbose_name_plural': 'Fechamentos mensais oficiais',
                'ordering': ['-ano', '-mes', 'turma__nome', 'disciplina__nome'],
                'unique_together': {('turma', 'disciplina', 'professor', 'mes', 'ano')},
            },
        ),
    ]
