# Generated by Django 6.0.5 on 2026-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='bimestre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='quantidade_aulas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diario',
            name='recursos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONCLUIDA', 'Concluída'), ('REVISAO', 'Enviar para revisão')], default='CONCLUIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='diario',
            name='tarefa_casa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
